### ISSUE TITLE
unable to open google drive file

### ISSUE THREAD

**Issue by Trupti100** [narendra478/Amazon-Clone-using-HTML-and-CSS#1]
unable to open google drive file. Please Reshare the google drive file.

**Comment by narendra478** [comment]
https://drive.google.com/drive/folders/1yxwYoJp8cQWBLlqgD7hygrb4OX9C-LWA?usp=sharing

**Comment by narendra478** [comment]
I have rectified the issue.

**Comment by Trupti100** [comment]
Thank You, Bro.

**Comment by narendra478** [comment]
My pleasure!
